[Kafka]
brokers=host.docker.internal:9092
group_id=comm-server-group
consume_topics = SEARCH
produce_topic = INFO

[Topic_SEARCH]
fields=serverId,characterName,characterId,type,action
action=dispatch


; 0R1_PjIxRc-g2xKUBcnfHw
; kafka-server-start $(brew --prefix)/etc/kafka/server.properties